version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3000
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=postgres://${DB_USERNAME}:${DB_PASSWORD}@host.docker.internal:5432/${DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
